### ISSUE TITLE
molpro_variables.ipynb corrupt xml output on Windows

### ISSUE THREAD

**Issue by nick-wilson** [molpro/pymolpro#15]
https://github.com/molpro/pymolpro/blob/master/docs/source/examples/molpro_variables.ipynb generates 

```
XMLSyntaxError: Char 0x0 out of allowed range, line 16, column 46
```
line 16 is:
```
    <irreducibleRepresentation index="1" id="...." cartesian=""/>
```

**Comment by pjknowles** [comment]
This bit of the xml is no longer generated in the release version of Molpro, and therefore there's nothing to fix.
