### ISSUE TITLE
Versioning of pymolpro messed up by Conda-forge 

### ISSUE THREAD

**Issue by pjknowles** [molpro/pymolpro#7]
```
% conda list |grep pymolpro
# packages in environment at /opt/homebrew/Caskroom/miniforge/base/envs/pymolpro-conda:
pymolpro                  0.1.2              pyhd8ed1ab_0    conda-forge

% python -c 'import pymolpro; print(pymolpro.__version__)'
0+untagged.24.g0d6a9fc.dirty
```

**Comment by nick-wilson** [comment]
From the documentation it looks as if setting parentdir_prefix in setup.cfg should work:
```
parentdir_prefix = pymolpro-
```
but when I tested it didn't help.

**Comment by nick-wilson** [comment]
The parentdir_prefix does work (normally).
The reason that it wasn't working for me is that my home directory is a git repository and it was picking up the tag from that.
Similarly for conda-forge it will pick up the tag from the feedstock.
There does not appear to be any way to disable the VCS check and the only VCS it supports is git so we can't just modify setup.cfg when building in conda-forge

**Comment by pjknowles** [comment]
So perhaps the way forward is to find an alternative to versioneer? Or simply get the version from the directory name, eliminating the fancy but unnecessary version reporting of developer copies of the package.

**Comment by nick-wilson** [comment]
versioneer works for all cases apart from when a distribution is unpacked inside a git repository so it's nearly there.

I tried an ugly hack to the conda-forge recipe to tag the feedstock repository to the pymolpro version:
```
  script: git tag {{ version }} ; {{ PYTHON }} -m pip install . -vv
```
and then it gives a version which is 0.1.3 but the hash is not correct:
```
(test) nickw@marat:~$ python -c 'import pymolpro; print(pymolpro.__version__)'
0.1.3+0.gea7f59a.dirty
```

**Comment by nick-wilson** [comment]
Another problem is that conda-forge renames the directory when it unpacks to something like:
```
build_artifacts/pymolpro_1666345270782/work
```
so ```parentdir_prefix``` test in versioneer won't work for conda-forge builds

**Comment by nick-wilson** [comment]
@pjknowles can you please pull PR#8 and make a new tag
Hopefully that will substitute version information into pymolpro/_version.py when GitHub creates the tarball with git-archive

**Comment by pjknowles** [comment]
> @pjknowles can you please pull PR#8 and make a new tag
> Hopefully that will substitute version information into pymolpro/_version.py when GitHub creates the tarball with git-archive

Done (I merged it to master since we certainly want those changes). The tag tarball from GitHub gets its version number correctly; let's see what happens when it goes through Conda-forge.

**Comment by pjknowles** [comment]
That's done the trick:
```
% python -c 'import pymolpro; print(pymolpro.__version__)'
0.1.6
```
